_core:
  default_config_hash: SwDzMQWH_m4gaInWZ_ioWc09pITzfAAMXNLS4dXs95U
select_registration_roles_setby_admin:
  admin: admin
  employee: employee
  administrator: '0'
select_registration_roles_admin_approval:
  administrator: '0'
  admin: '0'
  employee: '0'
select_registration_roles_auth_role: false
select_registration_roles_required: true
select_registration_roles_multiple: false
