<?php

/**
 * @file
 * Custom module for alteration and override drupal.
 */

use Drupal\Core\Url;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\views\Views;
use Drupal\file\Entity\File;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\File\FileSystemInterface;
use Drupal\image\Entity\ImageStyle;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\user\UserInterface;
/**
 * Submit handler for submit variant form.
 */

function user_module_user_presave(Drupal\Core\Entity\EntityInterface $entity) {
 if($entity->isNew()) {
   $entity->addRole('employee');
 }
}

/**
 * Implements hook_form_alter().
 */
function user_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {


  if ($form_id == 'node_attendance_form') {

  //  $form['title']['widget'][0]['value']['#value'] = 'The default title';
  $form['#validate'][] = '_form_validation_attendance';
   
  }
}

/**
 * Validation handler for submit message form.
 */
function _form_validation_attendance(&$form, FormStateInterface $form_state) 
{
  $current_user = \Drupal::currentUser();

$uid = $current_user->id();

$date = $form_state->getValue('field_punch_date')[0]['value'];
$database = \Drupal::database();
$results = $database->query("SELECT node_field_data.created AS node_field_data_created, node_field_data.nid AS nid, users_field_data_node_field_data.uid AS users_field_data_node_field_data_uid
FROM
{node_field_data} node_field_data
INNER JOIN {users_field_data} users_field_data_node_field_data ON node_field_data.uid = users_field_data_node_field_data.uid
LEFT JOIN {node__field_punch_date} node__field_punch_date ON node_field_data.nid = node__field_punch_date.entity_id AND node__field_punch_date.deleted = '0'
WHERE (node_field_data.status = '1') AND (node_field_data.type IN ('attendance')) AND (users_field_data_node_field_data.uid IN ('$uid')) AND ((DATE_FORMAT(node__field_punch_date.field_punch_date_value, '%Y-%m-%d') = DATE_FORMAT('$date', '%Y-%m-%d')))
ORDER BY node_field_data_created DESC
LIMIT 1 OFFSET 0")->fetchObject();
   if (isset($results->nid)) {
      $form_state->setErrorByName('field_punch_date', t('This Date Attendance Already Added.'));  
    }
    
       
}


/**
 * Implements hook_entity_presave().
 */
function user_module_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  switch ($entity->bundle()) {
    // Here you modify only your day content type
    case 'attendance':

$current_user = \Drupal::currentUser();

$uid = $current_user->id();

$user_mail = $current_user->getDisplayName();
      // Setting the title with the value of field_date.
      $entity->setTitle($user_mail. "-".$entity->get('field_punch_date')->value);
     break;
  }
}

 





/**
 * Add customers table relationship.
 */
function user_module_views_data_alter(array &$data) {
  $data['punch_time']['just_put_something_here'] = [
    'title' => t('Punch Table Relationship to User'),
    'relationship' => [
      'base' => 'users_field_data',
      'base field' => 'uid',
      'field' => 'user_id',
      'id' => 'standard',
      'label' => t('User Table Relationship'),
    ],
  ];

  $data['leave_details']['leave_type_re'] = [
    'title' => t('leave_type Relationship to User'),
    'relationship' => [
      'base' => 'taxonomy_term_field_data',
      'base field' => 'tid',
      'field' => 'type_id',
      'id' => 'standard',
      'label' => t('leave_type Table Relationship'),
    ],
  ];
  

}

/**
 * Implements hook_theme().
 */
function user_module_theme() {
  // Add order detail theme.
  $theme['admin_list_attendance'] = [
    'variables' => ['order_id' => NULL, 'data' => []],
    'template' => 'admin_list_attendance',
  ];
  // Add order detail theme.
  $theme['my_attendance'] = [
    'variables' => ['order_id' => NULL, 'data' => []],
    'template' => 'my_attendance',
  ];

  return $theme;
}




/**
 * Implements hook_page_attachments().
 */
function user_module_page_attachments(array &$page) {
 // $page['#attached']['drupalSettings']['api_url'] = api_url;
 // $page['#attached']['drupalSettings']['api_Authorization'] = api_Authorization;
  $page['#attached']['drupalSettings']['login'] = \Drupal::currentUser()->id();
}

/**
 * Implements hook_views_query_alter().
 */
function user_module_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\Sql  $query) {
  switch($view->storage->id()){
    case 'product_filter_api_test';

  //$query->addField(NULL, 'paragraphs_item_field_data_node__field_ex_showroom_city__paragraph__field_price.field_price_value', '', ['function' => 'sum']);
   // $query->addGroupBy('node_field_data.nid');
   
  // $query->addField('node_field_data', 'nid', '', ['function' => 'groupby']);
  //  $query->addGroupBy('node_field_data.nid');
   // $query->addField('node', 'nid', 'node_nid', array('function' => 'groupby'));
//Distinct = TRUE -used to avoid unnecessary groupby conditions
$query->distinct=TRUE;
 case 'my_leave';
 // $query->addField('leave_details', 'application_id', '', ['function' => 'max']);
//$query->addField('taxonomy_term_field_data_leave_details', 'tid', 'tid_1', array('function' => 'groupby'));
$query->addGroupBy('taxonomy_term_field_data_leave_details.tid');
 $query->distinct=TRUE;
    break;
  }
}


