# Schema for automail module configuration.
automail.settings:
  type: config_object
  label: 'Automail settings'
  mapping:
    bundle_list:
      type: sequence
      label: 'List of bundles'
    automail_subject:
      type: string
      label: 'Mail Subject in simple text'
    automail_body:
      type: string
      label: 'Mail body in formatted HTML'
    user_roles_list:
      type: sequence
      label: 'List of user roles'
